config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope "(:locale)", locale: /en|ru/ do
    devise_for :users, skip: :omniauth_callbacks
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'dictionaries#index'
    resources :dictionaries
    resources :words
    resources :lines
    get 'study/word_in_sentence', to: 'study#word_in_sentence'
    get 'study/word_and_translate', to: 'study#word_and_translate'
    get 'study/word_and_translate', to: 'study#word_and_translate'

  end
end

app/views/shared/_index.html.erb
<% if all %>
  <div class="digg_pagination"><div class="block-center"><%= will_paginate all, container: false, previous_label: '<', next_label: '>' %></div></div>
  <% all.each_with_index do |i, index| %>
    <div class="word_block">
      <ul class="item item_index">
        <li class="word"><span class="audio">
          <% if i.word %>
            <%= i.word.body %>
          <% end %>
        </span></li>
        <li class="word">
          <% if i.translation_words.first %>
            <%= i.translation_words.first.body %>
          <% end %>
        </li>
        <li>
          <div class="delete_button btn btn-primary" data-link="<%= dictionary_url(i.id) %>">Delete</div>
        </li>
      </ul>
      <% if i.image %>
        <% if i.image.body == "" %>
          <% image_correct = asset_path('no-image.png') %>
        <% end %>
        <% if i.image.body != "" %>
          <% image_correct = i.image.body %>
        <% end %>
      <% end %>
      <img class="custom_image" data-img="<%= image_correct %>">
    </div>
  <% end %>
  <div class="digg_pagination align-center"><div class="block-center"><%= will_paginate all, container: false, previous_label: '<', next_label: '>' %></div></div>
<% else %>
  Hello
<% end %>

app/views/shared/_index_copy.html.erb
<% if all %>
  <div class="digg_pagination"><div class="block-center"><%= will_paginate all, container: false, previous_label: '<', next_label: '>' %></div></div>
  <% all.each_with_index do |i, index| %>
    <div class="word_block">
      <ul class="item">
        <li class="word"><span class="audio"><%= i.word.body %></span></li>
        <li class="word"><%= i.translation_word.body %></li>
        <li class="line"><span class="audio"><%= i.line.body %></span></li>
        <li class="line"><%= i.translation_line.body %></li>
        <li class="remove">
          <!-- data: { confirm: 'Are you sure?' } -->
          <div class="delete_button btn btn-primary" data-link="<%= dictionary_url(i.id) %>">Delete</div>
          <a href="<%= edit_dictionary_url(i.id) %>" class="btn btn-primary">Edit</a>
        </li>
      </ul>
      <% if i.image.body == "" %>
        <% image_correct = asset_path('no-image.png') %>
      <% else %>
        <% image_correct = i.image.body %>
      <% end %>
      <img class="custom_image" data-img="<%= image_correct %>">
    </div>
  <% end %>
  <div class="digg_pagination align-center"><div class="block-center"><%= will_paginate all, container: false, previous_label: '<', next_label: '>' %></div></div>
<% else %>
  Hello
<% end %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t("your_dictionary"), root_url, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_url %>"><%= t("home") %></a></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= t("change_dictionary") %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="<%= new_word_url %>"><%= t("add_word") %></a></li>
              <li><a href="<%= new_line_url %>"><%= t("add_sentence") %></a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= t("learn") %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="<%= study_word_and_translate_path %>"><%= t("word_and_translate") %></a></li>
              <li><a href="#">method 2</a></li>
              <li><a href="#">method 3</a></li>
              <li><a href="#">method 4</a></li>
              <li><a href="#">method 5</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav">
        <li id="switch" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= t("language") %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu ul_language_dropdown">
            <li><%= link_to_unless_current "ru", locale: "ru" %></li>
            <li><%= link_to_unless_current "en", locale: "en" %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav ">
        <% unless user_signed_in? %>
          <li><a href="<%= new_user_session_url %>"><%= t("log_in") %></a></li>
        <% else %>
          <li><%= link_to t("log_out"), destroy_user_session_url, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% result = nil %>
<% flash.each do |name, msg| %>
  <% result = msg %>
<% end %>

<% if result %>
  <script>
    Messenger.options = {
      extraClasses: 'messenger-fixed messenger-on-top',
      theme: 'ice'
    }

    Messenger().post({
      message:"<%= result %>",
      showCloseButton: true,
      hideAfter: 7
    });
  </script>
<% end %>